<script setup>
defineProps({
    prompt: {
        type: String,
        default: '',
    },
    compact: {
        type: Boolean,
        default: false,
    },
});
</script>

<template>
    <div
        class="inline-flex max-w-full items-center gap-1.5 rounded-full bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700 ring-1 ring-inset ring-violet-200"
        :title="prompt || 'Generated by the AI reporting assistant'"
    >
        <span aria-hidden="true" class="text-violet-500">✦</span>
        <span>{{ compact ? 'AI' : 'AI report' }}</span>
    </div>
</template>
