<script setup>
import { Link, router } from '@inertiajs/vue3';
import AppLayout from '../../../../Layouts/AppLayout.vue';

defineProps({
    dashboard: {
        type: Object,
        required: true,
    },
    reports: {
        type: Array,
        default: () => [],
    },
    archivedReports: {
        type: Array,
        default: () => [],
    },
});

function archiveReport(report) {
    if (!confirm('Archive this saved report? It will be hidden from active lists but can be restored later.')) {
        return;
    }

    router.post(route('admin.reports.archive', report.id));
}

function restoreReport(report) {
    router.post(route('admin.reports.restore', report.id));
}

function formatDateTime(isoString) {
    if (!isoString) {
        return '—';
    }

    return new Date(isoString).toLocaleString();
}
</script>

<template>
    <AppLayout :title="`AI Reports · ${dashboard.name}`">
        <div class="mb-8 flex flex-wrap items-start justify-between gap-4">
            <div>
                <p class="text-sm text-slate-500">
                    <Link :href="route('admin.dashboards.show', dashboard.id)" class="hover:text-slate-700">
                        {{ dashboard.company_name }} · {{ dashboard.name }}
                    </Link>
                </p>
                <h1 class="text-3xl font-semibold">AI Reports</h1>
                <p class="mt-2 text-sm text-slate-600">Saved analytics queries generated by the reporting agent.</p>
            </div>
            <Link
                :href="route('admin.dashboards.reports.ask', dashboard.id)"
                class="rounded-lg bg-primary px-4 py-2 text-sm text-white hover:bg-primary-hover"
            >
                Ask a question
            </Link>
        </div>

        <div v-if="reports.length === 0" class="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">
            No active saved reports. Ask the AI agent a question about your analytics data.
        </div>

        <div v-else class="space-y-4">
            <div
                v-for="report in reports"
                :key="report.id"
                class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"
            >
                <div class="flex flex-wrap items-start justify-between gap-4">
                    <div class="min-w-0 flex-1">
                        <p class="text-sm text-slate-500">
                            {{ report.visualization_type.replace('_', ' ') }}
                            <span v-if="report.creator_name"> · {{ report.creator_name }}</span>
                        </p>
                        <h2 class="mt-1 text-lg font-semibold">{{ report.prompt }}</h2>
                        <pre class="mt-3 max-h-32 overflow-auto rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{{ report.sql }}</pre>
                    </div>
                    <button
                        type="button"
                        class="rounded-lg border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50"
                        @click="archiveReport(report)"
                    >
                        Archive
                    </button>
                </div>
            </div>
        </div>

        <section v-if="archivedReports.length > 0" class="mt-10">
            <h2 class="mb-4 text-lg font-semibold text-slate-700">Archived reports</h2>
            <div class="space-y-4">
                <div
                    v-for="report in archivedReports"
                    :key="report.id"
                    class="rounded-xl border border-slate-200 bg-slate-50 p-5"
                >
                    <div class="flex flex-wrap items-start justify-between gap-4">
                        <div class="min-w-0 flex-1">
                            <p class="text-sm text-slate-500">
                                Archived {{ formatDateTime(report.archived_at) }}
                                <span v-if="report.creator_name"> · {{ report.creator_name }}</span>
                            </p>
                            <h2 class="mt-1 text-lg font-semibold text-slate-800">{{ report.prompt }}</h2>
                            <p class="mt-1 text-sm text-slate-500">{{ report.visualization_type.replace('_', ' ') }}</p>
                        </div>
                        <button
                            type="button"
                            class="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-100"
                            @click="restoreReport(report)"
                        >
                            Restore
                        </button>
                    </div>
                </div>
            </div>
        </section>
    </AppLayout>
</template>
